export interface TrainerCreate{
    trainerId:number;
    trainerName:string;
    trainerSurname:string;
    trainerPassword:string;
    trainerBranch:string;
    addressName:string;
    trainerWage:number;
    formOfEduName:string;
    educationName:string;
    images:string[];
    trainerPhone:string
    trainerEmail:string
    trainerDate:string
    trainerGender:string
    trainerSchool:string
    trainerAbout:string
    aboutLessInfo:string
}